apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: parser-deployment
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
      - name: parser
        image: changyuan/evaluator
        ports: