language: python
env:
  - DB=sqlite
  - DB=postgres
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - cd webapp
  - pip install -r requirements.txt
before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS kubernetes_django;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE kubernetes_django;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE USER django WITH PASSWORD \'1a26d1g26d1gesb\';' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'grant all privileges on database kubernetes_django to django;' -U postgres; fi"
# command to run tests
script:
  - python manage.py test
  # - pytest
