# Generated by Django 2.1.5 on 2019-01-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pythonsnippet',
            old_name='last_process_sent',
            new_name='last_process_sent_p2',
        ),
        migrations.AddField(
            model_name='pythonsnippet',
            name='last_process_sent_p3',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pythonsnippet',
            name='python2_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pythonsnippet',
            name='python3_result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
