# Generated by Django 2.1.5 on 2019-01-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_snippets', '0002_auto_20190129_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonsnippet',
            name='execution_time_p2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pythonsnippet',
            name='execution_time_p3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pythonsnippet',
            name='status_code_p2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pythonsnippet',
            name='status_code_p3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
